name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: warn  # Set the global log level to suppress debug logs

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set a higher timeout, e.g., 30 minutes

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Rust components (clippy and rustfmt)
        run: rustup component add clippy rustfmt

      - name: Run tests with cargo
        run: cargo test --no-fail-fast

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Tarpaulin for Coverage
        run: cargo install cargo-tarpaulin

      - name: Run Coverage with Tarpaulin
        run: cargo tarpaulin --out Xml --all-features

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./cobertura.xml  # Ensure the path matches the output location of Tarpaulin
          token: ${{ secrets.CODECOV_TOKEN }}  # Use the secret here
